[tool.poetry]
name = "cli"
version = "0.1.0"
description = "Command-line interface to the Matchescu entity resolution comparison system"
authors = ["Andrei Olar <andrei.olar@ubbcluj.ro>"]
readme = "README.md"
packages = [{include = "matchescu", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"
matchescu-abstractions = {path = "../abstractions"}
matchescu-data-generators = {path = "../data-generators"}
pandas = "^2.0.3"
entity-resolution-measurements = {path = "../entity-resolution-measurements"}

[tool.poetry.scripts]
matchescu = "matchescu_cli.run:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
